export const AWS_BUCKET = 'tf-grapheq-prod-videos'
export const AWS_DEFAULT_REGION = 'us-west-2'
export const AWS_ACCOUNT_ID = '608181464701'
export const MONGO_STITCH_APP_ID = 'grapheq-staging-yxfio'
export const MONGO_STITCH_DB_NAME = 'grapheq'
